version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana_container
    restart: always
    user: "1000:1000"  # This sets the user to UID 1000, common for first user on Linux systems
    ports:
      - 3001:3000 # Changed from 3000 to 3001 got netbootzyz there
    networks:
      - monitoring_network
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,alexanderzobnin-zabbix-app
      - GF_DATASOURCES_TIMEOUT=60
      - GF_DATASOURCES_INFLUXDB_TIMEOUT=60
      - GF_PROXIES_DEFAULT_TIMEOUT=60
      - GF_DATAPROXY_TIMEOUT=60
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:latest
    container_name: influxdb_container
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring_network
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
      - ./influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-adminadmin12345}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-proxmox}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-proxmox}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-my-super-secret-admin-token}
      - INFLUXD_HTTP_BIND_ADDRESS=:8086
      - INFLUXDB_HTTP_READ_TIMEOUT=60s
      - INFLUXDB_HTTP_WRITE_TIMEOUT=60s
  telegraf:
    image: telegraf:latest
    container_name: telegraf_container
    restart: always
    ports:
      - 8089:8089/udp
    networks:
      - monitoring_network
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL:-http://influxdb:8086}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-my-super-secret-admin-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-proxmox}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-proxmox}
    depends_on:
      - influxdb
networks:
  monitoring_network:
    name: monitoring_network