version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana_container
    restart: always
    user: "1000:1000"  # This sets the user to UID 1000, common for first user on Linux systems
    ports:
      - 3001:3000 # Changed from 3000 to 3001 got netbootzyz there
    networks:
      - monitoring_network
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,alexanderzobnin-zabbix-app
  influxdb:
    image: influxdb:1.8
    container_name: influxdb_container
    restart: always
    ports:
      - 8086:8086
      - 8089:8089/udp
    networks:
      - monitoring_network
    volumes:
      - ./influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB:-proxmox}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}
      - INFLUXDB_USER=${INFLUXDB_USER:-proxmox}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-proxmox}
  telegraf:
    image: telegraf:latest
    container_name: telegraf_container
    restart: always
    networks:
      - monitoring_network
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - PROXMOX_HOST=${PROXMOX_HOST:-proxmox.local}
      - PROXMOX_USER=${PROXMOX_USER:-root@pam}
      - PROXMOX_TOKEN_ID=${PROXMOX_TOKEN_ID:-your_token_id}
      - PROXMOX_TOKEN_SECRET=${PROXMOX_TOKEN_SECRET:-your_token_secret}
      - INFLUXDB_URL=${INFLUXDB_URL:-http://influxdb:8086}
      - INFLUXDB_DB=${INFLUXDB_DB:-proxmox}
      - INFLUXDB_USER=${INFLUXDB_USER:-proxmox}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-proxmox}
    depends_on:
      - influxdb
networks:
  monitoring_network:
    name: monitoring_network